# -*- coding: utf-8 -*-
"""nvda_options_engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oi_xfShU0DcuPk9UciGKNlAD85AQjvsE
"""

"""
Option Pricing & Discrete Delta-Hedging Risk Engine
====================================================
Black-Scholes pricer with full analytical Greeks, Newton-Raphson implied
volatility extraction, and a Monte Carlo simulation of discrete
delta-hedging tracking error ("Gamma bleed") calibrated on live option
market data via yfinance.

Author: Emile Roumieux
"""

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from scipy.stats import norm
from typing import Dict, Tuple, Union

# =====================================================================
# 1. PRICING & GREEKS ENGINE
# =====================================================================

def vectorized_bs_greeks(
    S: Union[float, np.ndarray],
    K: float,
    T: Union[float, np.ndarray],
    r: float,
    sigma: float,
    option_type: str = "call",
) -> Dict[str, Union[float, np.ndarray]]:
    """Vectorized Black-Scholes pricer and analytical Greeks engine.

    Supports scalar or NumPy array inputs for S and T, so the same function
    prices a single option or an entire simulated path grid at once.
    """
    T_safe = np.maximum(T, 1e-5)
    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T_safe) / (sigma * np.sqrt(T_safe))
    d2 = d1 - sigma * np.sqrt(T_safe)

    n_d1, n_d2, pdf_d1 = norm.cdf(d1), norm.cdf(d2), norm.pdf(d1)

    if option_type.lower() == "call":
        price = S * n_d1 - K * np.exp(-r * T_safe) * n_d2
        delta = n_d1
        theta = (-(S * pdf_d1 * sigma) / (2 * np.sqrt(T_safe)) - r * K * np.exp(-r * T_safe) * n_d2) / 365.0
        rho = K * T_safe * np.exp(-r * T_safe) * n_d2 / 100.0
    elif option_type.lower() == "put":
        price = K * np.exp(-r * T_safe) * norm.cdf(-d2) - S * norm.cdf(-d1)
        delta = n_d1 - 1.0
        theta = (-(S * pdf_d1 * sigma) / (2 * np.sqrt(T_safe)) + r * K * np.exp(-r * T_safe) * norm.cdf(-d2)) / 365.0
        rho = -K * T_safe * np.exp(-r * T_safe) * norm.cdf(-d2) / 100.0
    else:
        raise ValueError("option_type must be 'call' or 'put'")

    gamma = pdf_d1 / (S * sigma * np.sqrt(T_safe))
    vega = (S * np.sqrt(T_safe) * pdf_d1) / 100.0

    return {"price": price, "delta": delta, "gamma": gamma, "vega": vega, "theta": theta, "rho": rho}


def implied_vol_newton(
    market_price: float,
    S: float,
    K: float,
    T: float,
    r: float,
    option_type: str = "call",
    tol: float = 1e-6,
    max_iter: int = 100,
    sigma_bounds: Tuple[float, float] = (1e-4, 5.0),
) -> float:
    """Extracts implied volatility via Newton-Raphson.

    Bounds are enforced at every step: without them, a stale or zero
    quote can push sigma negative, which then crashes the downstream
    Monte Carlo simulation (np.random.normal rejects a negative scale).
    """
    sigma = 0.3  # reasonable seed for equities
    for _ in range(max_iter):
        res = vectorized_bs_greeks(S, K, T, r, sigma, option_type)
        diff = res["price"] - market_price
        if abs(diff) < tol:
            return float(np.clip(sigma, *sigma_bounds))

        raw_vega = res["vega"] * 100.0  # undo the 1%-move scaling to get the true derivative
        if abs(raw_vega) < 1e-8:
            break  # vega too flat to make progress (deep ITM/OTM or near expiry)

        sigma = float(np.clip(sigma - diff / raw_vega, *sigma_bounds))

    return sigma


def test_put_call_parity() -> None:
    """Validates the pricer against put-call parity: C - P = S - K*e^(-rT)."""
    S, K, T, r, sigma = 100.0, 100.0, 1.0, 0.05, 0.2
    c_price = vectorized_bs_greeks(S, K, T, r, sigma, "call")["price"]
    p_price = vectorized_bs_greeks(S, K, T, r, sigma, "put")["price"]
    assert np.isclose(c_price - p_price, S - K * np.exp(-r * T)), "Put-Call Parity failed!"
    print("Put-Call Parity test passed")


# =====================================================================
# 2. DISCRETE HEDGING & PnL SIMULATION
# =====================================================================

def simulate_discrete_hedging_pnl(
    S0: float,
    K: float,
    r: float,
    sigma: float,
    T: float,
    option_price: float,
    steps: int = 63,
    paths: int = 1000,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Simulates underlying paths and the P&L of a discretely rebalanced
    delta-hedge replicating a long call.

    The replicating portfolio is seeded with the option's actual traded
    premium (Pi_0 = option_price), not zero -- this is what makes the
    residual reflect pure discretization error ("Gamma bleed") instead of
    a missing-capital artifact roughly equal to the premium itself.

    Paths are simulated under the risk-neutral measure (drift = r), and the
    same sigma is used both to generate paths and to compute hedge ratios.
    This isolates the effect of discrete vs. continuous rebalancing from
    any model or volatility misspecification.
    """
    dt = T / steps
    np.random.seed(42)

    increments = np.random.normal(
        loc=(r - 0.5 * sigma ** 2) * dt, scale=sigma * np.sqrt(dt), size=(paths, steps)
    )
    log_paths = np.zeros((paths, steps + 1))
    log_paths[:, 1:] = np.cumsum(increments, axis=1)
    S_paths = S0 * np.exp(log_paths)

    time_grid = np.linspace(T, 1e-5, steps + 1)
    deltas = np.zeros((paths, steps + 1))
    for t_idx in range(steps + 1):
        deltas[:, t_idx] = vectorized_bs_greeks(S_paths[:, t_idx], K, time_grid[t_idx], r, sigma, "call")["delta"]

    # Self-financing replicating portfolio, seeded with the option premium
    # (the fix): Pi_0 = delta_0 * S_0 + cash_0 = option_price.
    cash = option_price - deltas[:, 0] * S_paths[:, 0]
    for t in range(1, steps + 1):
        cash = cash * np.exp(r * dt) - (deltas[:, t] - deltas[:, t - 1]) * S_paths[:, t]

    portfolio_value = deltas[:, -1] * S_paths[:, -1] + cash
    payoff = np.maximum(S_paths[:, -1] - K, 0)
    tracking_error = payoff - portfolio_value  # residual "Gamma bleed"

    return S_paths, deltas, tracking_error


# =====================================================================
# 3. LIVE DATA & EXECUTION
# =====================================================================

def fetch_live_atm_option(ticker: str = "NVDA") -> Tuple[float, float, float, float]:
    """Fetches the nearest-expiry, at-the-money call from live market data.

    Falls back to the bid/ask midpoint when `lastPrice` is stale or zero,
    which is common for thinly traded strikes.
    """
    tkr = yf.Ticker(ticker)
    hist = tkr.history(period="1d")
    S0 = hist["Close"].iloc[-1]

    expirations = tkr.options
    if not expirations:
        raise ValueError("No options data available.")

    near_expiry = expirations[0]
    opt_chain = tkr.option_chain(near_expiry)
    calls = opt_chain.calls

    atm_call = calls.iloc[(calls["strike"] - S0).abs().argsort()[:1]]
    K = float(atm_call["strike"].values[0])
    last_price = float(atm_call["lastPrice"].values[0])
    bid = float(atm_call["bid"].values[0])
    ask = float(atm_call["ask"].values[0])

    market_price = (bid + ask) / 2.0 if (last_price <= 0 and bid > 0 and ask > 0) else last_price
    if market_price <= 0:
        raise ValueError(f"No usable quote for {ticker} {near_expiry} {K}C.")

    days_to_expiry = (pd.to_datetime(near_expiry) - pd.Timestamp.today()).days
    T = max(days_to_expiry / 365.0, 1 / 365.0)

    return S0, K, T, market_price


if __name__ == "__main__":
    test_put_call_parity()

    r_risk_free = 0.045
    ticker = "NVDA"

    try:
        print(f"\nFetching live data for {ticker}...")
        S0, K, T, market_price = fetch_live_atm_option(ticker)
        print(f"Spot: ${S0:.2f} | ATM Strike: ${K} | T: {T:.4f}y | Option Price: ${market_price:.2f}")
    except Exception as e:
        print(f"Live data fetch failed ({e}). Using fallback data.")
        S0, K, T, market_price = 120.0, 120.0, 0.25, 5.50

    implied_vol = implied_vol_newton(market_price, S0, K, T, r_risk_free)
    print(f"Calculated Implied Volatility: {implied_vol:.2%}")

    # Rebalancing frequency scales with the actual horizon fetched instead
    # of a hardcoded 63 (~1 quarter of daily rebalances), which no longer
    # means "daily" once T comes from a live, possibly much shorter, expiry.
    steps = max(int(round(T * 252)), 5)

    print(f"Simulating discrete delta-hedging tracking error ({steps} rebalances)...")
    S_paths, deltas, tracking_error = simulate_discrete_hedging_pnl(
        S0, K, r_risk_free, implied_vol, T, option_price=market_price, steps=steps
    )

    print(f"Mean tracking error: ${tracking_error.mean():.4f}  (should be close to $0)")
    print(f"Std tracking error:  ${tracking_error.std():.4f}")

    plt.figure(figsize=(8, 5))
    plt.hist(tracking_error, bins=50, color="steelblue", alpha=0.7, edgecolor="black")
    plt.axvline(tracking_error.mean(), color="red", linestyle="dashed", linewidth=2,
                label=f"Mean PnL: ${tracking_error.mean():.2f}")
    plt.title("Discrete Hedging Tracking Error Distribution (Gamma Bleed)")
    plt.xlabel("PnL Error ($)")
    plt.ylabel("Frequency")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("hedging_tracking_error.png", dpi=300)
    plt.show()